services:
  - type: web
    name: qltime-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: qltime-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES
        value: 1d
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    
databases:
  - name: qltime-mongodb
    databaseName: qltime
    user: qltime-user
